language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - git config --global url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf
    "https://github.com/"

after_success:
- npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
